# Generated by Django 5.2.1 on 2025-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiloMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo_name', models.CharField(max_length=50, verbose_name='サイロNo')),
                ('disabled', models.BooleanField(default=False, verbose_name='直接入庫対象外')),
                ('inbound_max_weight', models.IntegerField(verbose_name='最大入庫量')),
                ('max_weight', models.IntegerField(verbose_name='最大容量')),
                ('should_calculate', models.BooleanField(default=False, verbose_name='計算対象')),
            ],
            options={
                'verbose_name': 'サイロマスタ',
                'verbose_name_plural': 'サイロマスタ',
                'db_table': 'silo_master',
                'ordering': ['silo_name'],
            },
        ),
    ]
