# Generated by Django 5.2.1 on 2025-06-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_rogic_sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiloFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_text', models.TextField(blank=True, null=True, verbose_name='計算式の内容')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明')),
                ('silo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='silo_rogic_sample.silomaster')),
            ],
            options={
                'verbose_name': 'サイロ計算式',
                'verbose_name_plural': 'サイロ計算式',
                'db_table': 'silo_formula',
            },
        ),
    ]
