# Generated by Django 5.2.1 on 2025-06-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_rogic_sample', '0002_siloformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='silomaster',
            name='should_compare_with_others',
            field=models.BooleanField(default=False, verbose_name='他サイロとの比較対象'),
        ),
        migrations.CreateModel(
            name='SiloCompare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_source', to='silo_rogic_sample.silomaster', verbose_name='比較元サイロ')),
                ('target_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_target', to='silo_rogic_sample.silomaster', verbose_name='比較先サイロ')),
            ],
            options={
                'verbose_name': 'サイロ比較',
                'verbose_name_plural': 'サイロ比較',
                'db_table': 'silo_compare',
            },
        ),
    ]
