# Generated by Django 5.2.1 on 2025-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_rogic_sample', '0003_silomaster_should_compare_with_others_silocompare'),
    ]

    operations = [
        migrations.AddField(
            model_name='silocompare',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='比較する計算式の内容'),
        ),
    ]
